<?php
  #不包含header footer和交互
  header('ACCESS-CONTROL-ALLOW-ORIGIN:*');
  $arr = [
    'code'=>200,
    'data'=>[
      'bookContent'=>[
        'id'=>12,
        'bookName'=>'时光和你我都要',
        'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
        'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
        'author'=>'喝芬达的兔',
        'label'=>'现代言情',
        'color'=>'#7FBEDB',
        'numberWords'=>'48123',
        'isVip'=>0,
        'many'=>'0.05喜点/千字'
      ],
      'catalog'=>[
        'state'=>'连载中',
        'number'=>1024,
        'list'=>[
          [
          'id'=>1001,
          'chapterName'=>'第一百章 好汉不吃眼前亏',
          'chapterTime'=>'2020-12-31 12:00:42'
          ]
        ]
      ],
      'bookReview'=>[
        'number'=>32134,
        'list'=>[
          [
            'id'=>233,
            'reviewUser'=>'奥特曼',
            'portrait'=>'https://fdfs.xmcdn.com/group43/M03/75/FF/wKgKjVr0AkKiOrikAAB5drM3PYU014.jpg',
            'reviewTitle'=>'这什么垃圾书？',
            'reviewContent'=>'操你妈，垃圾书，老子不看了。垃圾作者！',
            'reviewTime'=>'8小时前 '
          ],
          [
            'id'=>234,
            'reviewUser'=>'我吃西红柿',
            'portrait'=>'https://static.qijizuopin.com/images/web/default.png',
            'reviewTitle'=>'所有喷作者的',
            'reviewContent'=>'爱看看不看滚',
            'reviewTime'=>'7小时前 '
          ],
          [
            'id'=>235,
            'reviewUser'=>'奥特曼',
            'portrait'=>'https://fdfs.xmcdn.com/group43/M03/75/FF/wKgKjVr0AkKiOrikAAB5drM3PYU014.jpg',
            'reviewTitle'=>'这什么垃圾书？',
            'reviewContent'=>'操你妈，垃圾书，老子不看了。垃圾作者！',
            'reviewTime'=>'6小时前 '
          ],
          [
            'id'=>236,
            'reviewUser'=>'天蚕土豆',
            'portrait'=>'https://static.qijizuopin.com/images/web/default.png',
            'reviewTitle'=>'那些喷的人什么心态？',
            'reviewContent'=>'人家作者写书容易吗？你牛逼你怎么不去写一本？傻逼。',
            'reviewTime'=>'5小时前 '
          ],
          [
            'id'=>237,
            'reviewUser'=>'专打奥特曼',
            'portrait'=>'https://static.qijizuopin.com/images/web/default.png',
            'reviewTitle'=>'那个什么奥特曼',
            'reviewContent'=>'就你这J8素质，奥特曼的脸都让你丢光了OK？',
            'reviewTime'=>'4小时前 '
          ]
        ]
      ],
      'otherBooks'=>[
        [
          'id'=>13,
          'bookName'=>'美女的贴身私教',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
          'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
          'author'=>'朱公子',
          'label'=>'都市小说',
          'numberWords'=>'165812'
        ],
        [
          'id'=>14,
          'bookName'=>'无尽星海',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
          'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
          'author'=>'蔚蓝',
          'label'=>'科幻末世',
          'numberWords'=>'88200'
        ]
      ],
      'hot'=>[
        [
          'id'=>15,
          'bookName'=>'美女的贴身私教',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
          'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
          'author'=>'朱公子',
          'label'=>'都市小说',
          'numberWords'=>'165812'
        ],
        [
          'id'=>16,
          'bookName'=>'无尽星海',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
          'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
          'author'=>'蔚蓝',
          'label'=>'科幻末世',
          'numberWords'=>'88200'
        ],
        [
          'id'=>17,
          'bookName'=>'美女的贴身私教',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
          'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
          'author'=>'朱公子',
          'label'=>'都市小说',
          'numberWords'=>'165812'
        ],
        [
          'id'=>18,
          'bookName'=>'无尽星海',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
          'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
          'author'=>'蔚蓝',
          'label'=>'科幻末世',
          'numberWords'=>'88200'
        ],
        [
          'id'=>19,
          'bookName'=>'无尽星海',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
          'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
          'author'=>'蔚蓝',
          'label'=>'科幻末世',
          'numberWords'=>'88200'
        ],
        [
          'id'=>20,
          'bookName'=>'美女的贴身私教',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
          'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
          'author'=>'朱公子',
          'label'=>'都市小说',
          'numberWords'=>'165812'
        ]
      ]
    ],
    'msg'=>'服务器连接错误'
  ];
	exit(json_encode($arr));
?>