<?php
  #不包含header footer和交互
  header('ACCESS-CONTROL-ALLOW-ORIGIN:*');
  $arr = [
    'code'=>200,
    'data'=>[
      'banner'=>[
        [
          'id'=>1,
          'name'=>'轮回元帝',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/banner/0JnjIaACTF.jpg?imageView2/1/'
        ],
        [
          'id'=>2,
          'name'=>'我在山村支教那些年',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/banner/RZhH7eqwD6.png?imageView2/1/'
        ],
        [
          'id'=>3,
          'name'=>'总裁的头号甜心',
          'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/banner/GBvVciULzd.png?imageView2/1/'
        ]
      ],
      'recommend'=>[
        [
          'id'=>1,
          'template_id'=>1,
          'name'=>'重磅推荐',
          'list'=>[
            [
              'id'=>1,
              'bookName'=>'轮回元帝',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/06/WMannXn5D9.jpg?imageView2/1/w/200/h/267',
              'brief'=>'灵气复苏，天下分崩。秦南十年一梦，重生而来。',
              'author'=>'九鼎问天',
              'label'=>'都市小说',
              'numberWords'=>'21345',
              'color'=>'#7FBEDB'
            ],
            [
              'id'=>2,
              'bookName'=>'时光和你我都要',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
              'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
              'author'=>'喝芬达的兔',
              'label'=>'现代言情',
              'numberWords'=>'48123',
              'color'=>'#7FBEDB'
            ],
            [
              'id'=>3,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812',
              'color'=>'#7FBEDB'
            ],
            [
              'id'=>4,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200',
              'color'=>'#7FBEDB'
            ]
          ]
        ],
        [
          'id'=>2,
          'name'=>'完结精品',
          'template_id'=>2,
          'list'=>[
            [
              'id'=>5,
              'bookName'=>'轮回元帝',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/06/WMannXn5D9.jpg?imageView2/1/w/200/h/267',
              'brief'=>'灵气复苏，天下分崩。秦南十年一梦，重生而来。',
              'author'=>'九鼎问天',
              'label'=>'都市小说',
              'numberWords'=>'21345'
            ],
            [
              'id'=>6,
              'bookName'=>'时光和你我都要',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
              'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
              'author'=>'喝芬达的兔',
              'label'=>'现代言情',
              'numberWords'=>'48123'
            ],
            [
              'id'=>7,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>8,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ],
            [
              'id'=>9,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>10,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ]
          ]
        ],
        [
          'id'=>3,
          'name'=>'连载畅销',
          'template_id'=>2,
          'list'=>[
            [
              'id'=>11,
              'bookName'=>'轮回元帝',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/06/WMannXn5D9.jpg?imageView2/1/w/200/h/267',
              'brief'=>'灵气复苏，天下分崩。秦南十年一梦，重生而来。',
              'author'=>'九鼎问天',
              'label'=>'都市小说',
              'numberWords'=>'21345'
            ],
            [
              'id'=>12,
              'bookName'=>'时光和你我都要',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
              'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
              'author'=>'喝芬达的兔',
              'label'=>'现代言情',
              'numberWords'=>'48123'
            ],
            [
              'id'=>13,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>14,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ],
            [
              'id'=>15,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>16,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ]
          ]
        ],
        [
          'id'=>4,
          'name'=>'限时免费',
          'template_id'=>2,
          'list'=>[
            [
              'id'=>17,
              'bookName'=>'轮回元帝',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/06/WMannXn5D9.jpg?imageView2/1/w/200/h/267',
              'brief'=>'灵气复苏，天下分崩。秦南十年一梦，重生而来。',
              'author'=>'九鼎问天',
              'label'=>'都市小说',
              'numberWords'=>'21345'
            ],
            [
              'id'=>18,
              'bookName'=>'时光和你我都要',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
              'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
              'author'=>'喝芬达的兔',
              'label'=>'现代言情',
              'numberWords'=>'48123'
            ],
            [
              'id'=>19,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>20,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ],
            [
              'id'=>21,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>22,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ]
          ]
        ],
        [
          'id'=>5,
          'name'=>'新书推荐',
          'template_id'=>3,
          'list'=>[
            [
              'id'=>23,
              'bookName'=>'轮回元帝',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/06/WMannXn5D9.jpg?imageView2/1/w/200/h/267',
              'brief'=>'灵气复苏，天下分崩。秦南十年一梦，重生而来。',
              'author'=>'九鼎问天',
              'label'=>'都市小说',
              'numberWords'=>'21345',
              'color'=>'#7FBEDB'
            ],
            [
              'id'=>24,
              'bookName'=>'时光和你我都要',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
              'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
              'author'=>'喝芬达的兔',
              'label'=>'现代言情',
              'numberWords'=>'48123',
              'color'=>'#7487C1'
            ],
            [
              'id'=>25,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812',
              'color'=>'#7FBEDB'
            ],
            [
              'id'=>26,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200',
              'color'=>'#B5E2B5'
            ],
            [
              'id'=>27,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812',
              'color'=>'#7FBEDB'
            ],
            [
              'id'=>28,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200',
              'color'=>'#B5E2B5'
            ]
          ]
        ],
        [
          'id'=>6,
          'name'=>'男生最爱',
          'template_id'=>2,
          'list'=>[
            [
              'id'=>29,
              'bookName'=>'轮回元帝',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/06/WMannXn5D9.jpg?imageView2/1/w/200/h/267',
              'brief'=>'灵气复苏，天下分崩。秦南十年一梦，重生而来。',
              'author'=>'九鼎问天',
              'label'=>'都市小说',
              'numberWords'=>'21345'
            ],
            [
              'id'=>30,
              'bookName'=>'时光和你我都要',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
              'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
              'author'=>'喝芬达的兔',
              'label'=>'现代言情',
              'numberWords'=>'48123'
            ],
            [
              'id'=>31,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>32,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ],
            [
              'id'=>33,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>34,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ]
          ]
        ],
        [
          'id'=>7,
          'name'=>'女生最爱',
          'template_id'=>2,
          'list'=>[
            [
              'id'=>35,
              'bookName'=>'轮回元帝',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/06/WMannXn5D9.jpg?imageView2/1/w/200/h/267',
              'brief'=>'灵气复苏，天下分崩。秦南十年一梦，重生而来。',
              'author'=>'九鼎问天',
              'label'=>'都市小说',
              'numberWords'=>'21345'
            ],
            [
              'id'=>36,
              'bookName'=>'时光和你我都要',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/05/16/uzBUouQDMw.jpg?imageView2/1/w/200/h/267',
              'brief'=>'十七岁不良少女雪珞重生了。当她醒来发现自己回到五年前的那一刻，她开始重新规划自己的人生。改头换面、变身学霸、惩恶扬善、套路男神……她要改变前世的命运，报仇雪耻，赢得美男归。',
              'author'=>'喝芬达的兔',
              'label'=>'现代言情',
              'numberWords'=>'48123'
            ],
            [
              'id'=>37,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>38,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ],
            [
              'id'=>39,
              'bookName'=>'美女的贴身私教',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/04/K2OXgTQyOK.jpg?imageView2/1/w/200/h/267',
              'brief'=>'身为一名私人教练，李修要做的事情，就是让他的会员摆脱不完美！女明星腰痛？来来来，我给你上两节私教课，包治百病！武林高手遭遇突破瓶颈？来来来，来上我的私教课，包你修为突飞猛进！这个世界上没有什么不完美的人，如果有，那是因为他们没有遇到我。',
              'author'=>'朱公子',
              'label'=>'都市小说',
              'numberWords'=>'165812'
            ],
            [
              'id'=>40,
              'bookName'=>'无尽星海',
              'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/cover/2018/06/20/oFBBJnMbpW.jpg?imageView2/1/w/200/h/267',
              'brief'=>'每一个轮回之时都会出现命运之子，每一次都会为宇宙填上一笔曙光，只当宿命重叠只时，背负着使命，阿瑞斯的诸王，地球文明的存亡，前世的爱恨情仇，还有那藏在幕后人物，一切都逼着他变大强大！',
              'author'=>'蔚蓝',
              'label'=>'科幻末世',
              'numberWords'=>'88200'
            ]
          ]
        ]
      ],
      'special'=>[
        'id'=>1,
        's_name'=>'专题推荐',
        'list'=>[
          [
            'id'=>1,
            's_name'=>'专题1',
            'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/banner/OfkjuVGphO.png?imageView2/1/'
          ],
          [
            'id'=>2,
            's_name'=>'专题2',
            'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/banner/RZhH7eqwD6.png?imageView2/1/'
          ],
          [
            'id'=>3,
            's_name'=>'专题3',
            'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/banner/GBvVciULzd.png?imageView2/1/'
          ],
          [
            'id'=>4,
            's_name'=>'专题4',
            'imgUrl'=>'https://qijiupload-1251952132.picsh.myqcloud.com/storage/uploads/banner/qKNeTkjDK8.jpg?imageView2/1/'
          ]
        ]
      ]
    ],
    'msg'=>'服务器连接错误'
  ];
	exit(json_encode($arr));
?>